<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-11-18 16:53

$extensionPath = t3lib_extMgm::extPath('alumnilist');
return array(
	'tx_alumnilist_controller_alumnuscontroller' => $extensionPath . 'Classes/Controller/AlumnusController.php',
	'tx_alumnilist_controller_coursecontroller' => $extensionPath . 'Classes/Controller/CourseController.php',
	'tx_alumnilist_controller_yearcontroller' => $extensionPath . 'Classes/Controller/YearController.php',
	'tx_alumnilist_domain_exception_wrongyearexception' => $extensionPath . 'Classes/Domain/Exception/WrongYearException.php',
	'tx_alumnilist_domain_model_alumnus' => $extensionPath . 'Classes/Domain/Model/Alumnus.php',
	'tx_alumnilist_domain_model_alumnuschecksum' => $extensionPath . 'Classes/Domain/Model/AlumnusChecksum.php',
	'tx_alumnilist_domain_model_course' => $extensionPath . 'Classes/Domain/Model/Course.php',
	'tx_alumnilist_domain_model_year' => $extensionPath . 'Classes/Domain/Model/Year.php',
	'tx_alumnilist_domain_repository_alumnuschecksumrepository' => $extensionPath . 'Classes/Domain/Repository/AlumnusChecksumRepository.php',
	'tx_alumnilist_domain_repository_alumnuschecksumrepositoryinterface' => $extensionPath . 'Classes/Domain/Repository/AlumnusChecksumRepositoryInterface.php',
	'tx_alumnilist_domain_repository_alumnusrepository' => $extensionPath . 'Classes/Domain/Repository/AlumnusRepository.php',
	'tx_alumnilist_domain_repository_alumnusrepositoryinterface' => $extensionPath . 'Classes/Domain/Repository/AlumnusRepositoryInterface.php',
	'tx_alumnilist_domain_repository_yearrepository' => $extensionPath . 'Classes/Domain/Repository/YearRepository.php',
	'tx_alumnilist_domain_repository_yearrepositoryinterface' => $extensionPath . 'Classes/Domain/Repository/YearRepositoryInterface.php',
	'tx_alumnilist_domain_service_alumnuschecksumservice' => $extensionPath . 'Classes/Domain/Service/AlumnusChecksumService.php',
	'tx_alumnilist_domain_service_alumnuschecksumserviceinterface' => $extensionPath . 'Classes/Domain/Service/AlumnusChecksumServiceInterface.php',
	'tx_alumnilist_controller_alumnuscontrollertest' => $extensionPath . 'Tests/Unit/Controller/AlumnusControllerTest.php',
	'tx_alumnilist_controller_coursecontrollertest' => $extensionPath . 'Tests/Unit/Controller/CourseControllerTest.php',
	'tx_alumnilist_controller_yearcontrollertest' => $extensionPath . 'Tests/Unit/Controller/YearControllerTest.php',
	'tx_alumnilist_domain_model_alumnuschecksumtest' => $extensionPath . 'Tests/Unit/Domain/Model/AlumnusChecksumTest.php',
	'tx_alumnilist_domain_model_alumnustest' => $extensionPath . 'Tests/Unit/Domain/Model/AlumnusTest.php',
	'tx_alumnilist_domain_model_coursetest' => $extensionPath . 'Tests/Unit/Domain/Model/CourseTest.php',
	'tx_alumnilist_domain_model_yeartest' => $extensionPath . 'Tests/Unit/Domain/Model/YearTest.php',
	'tx_alumnilist_domain_repository_alumnusrepositorymock' => $extensionPath . 'Tests/Unit/Domain/Repository/AlumnusRepositoryMock.php',
);
?>